name: build packages

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install makepkg updpkgsums namcap
    - name: update source hashes
      run: updpkgsums
      working-directory: ${{github.workspace}}/clients
    - name: check PKGBUILD
      run: namcap PKGBUILD
      working-directory: ${{github.workspace}}/clients
