name: build packages

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install pacman
      run: sudo apt-get update && sudo apt-get install pacman-package-manager
    - name: Install dependencies
      run: sudo pacman --noconfirm -S pacman-contrib
    - name: update source hashes
      run: updpkgsums
      working-directory: ${{github.workspace}}/clients
    - name: check PKGBUILD
      run: namcap PKGBUILD
      working-directory: ${{github.workspace}}/clients
