name: build packages

on:
  push:


jobs:
  build-arch-package:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup builder user
      run: 'mkdir -p /etc/sudoers.d && useradd -m builder && echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder && chmod -R 777 .'
    - name: Install dependencies
      run: pacman --noconfirm -Sy pacman-contrib namcap nodejs
    - name: update source hashes
      run: runuser -u builder -- updpkgsums
      working-directory: ${{github.workspace}}/clients
    - name: check PKGBUILD
      run: 'if [ -n "$(runuser -u builder -- namcap -m PKGBUILD)" ]; then (namcap PKGBUILD; exit 1) else (exit 0) fi'
      working-directory: ${{github.workspace}}/clients
    - name: makepkg
      run: runuser -u builder -- makepkg --syncdeps --noconfirm --rmdeps
      working-directory: ${{github.workspace}}/clients
    - name: Attest
      id: attest
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: '${{github.workspace}}/clients/*.pkg.tar.zst'
    - name: Copy attestation file
      if: startsWith(github.ref, 'refs/tags/')
      run: cp $BUNDLE arch-bundle-attestation.jsonl
      env:
        BUNDLE: ${{steps.attest.outputs.bundle-path}}
    - uses: actions/upload-artifact@v4
      with:
        name: arch-package
        path: '${{github.workspace}}/clients/*.pkg.tar.zst'
        if-no-files-found: error
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          clients/*.pkg.tar.zst
          arch-bundle-attestation.jsonl

  test-arch-package:
    runs-on: ubuntu-latest
    container: archlinux:base
    needs: build-arch-package

    steps:
    - name: Setup builder user
      run: 'mkdir -p /etc/sudoers.d && useradd -m builder && echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder && chmod -R 777 .'
    - name: install node
      run: pacman -Sy --noconfirm nodejs
    - uses: actions/download-artifact@v4
      with:
        name: arch-package
    - name: Display structure of downloaded files
      run: ls -R
    - name: Install the package
      run: pacman -U --noconfirm *.pkg.tar.zst
    - name: Run the check
      run: /usr/lib/restic-backup-client/index.js check

  build-deb-package:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    needs: build-arch-package
    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: apt update && apt install -y pacman-package-manager nodejs sudo zstd
    - name: create target directory
      run: mkdir -p target
    - uses: actions/download-artifact@v4
      with:
        name: arch-package
    - name: ls
      run: ls -l
    - name: Setup builder user
      run: 'useradd -m builder && echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder && chmod -R 777 .'
    - name: prepare data directory
      run: tar --zstd -xvf *.pkg.tar.zst -C ./target
    - name: remove files from data directory
      run: find . -maxdepth 1 -type f -delete
      working-directory: ${{github.workspace}}/target
    - name: makepkg
      run: runuser -u builder -- makepkg --printsrcinfo > .SRCINFO
      working-directory: ${{github.workspace}}/clients
    - name: setup control file
      run: |
        cat .SRCINFO | awk '$1 == "pkgname" {print "Package: " substr($0, index($0,"= ")+2)}' >> control
        cat .SRCINFO | awk '$1 == "pkgver" {version = substr($0, index($0,"= ")+2)} $1 == "pkgrel" {rel = substr($0, index($0,"= ")+2)} END{print "Version: " version "-" rel}' >> control
        cat .SRCINFO | awk '$1 == "pkgdesc" {print "Description: " substr($0, index($0,"= ")+2)}' >> control
        cat .SRCINFO | awk '$1 == "arch" {print "Architecture: " substr($0, index($0,"= ")+2)}' >> control
        cat .SRCINFO | awk '$1 == "license" {print "License: " substr($0, index($0,"= ")+2)}' >> control
        cat PKGBUILD | awk 'index($0, "Maintainer:") {print "Maintainer: " substr($0, index($0,": ")+2)}' >> control
        cat .SRCINFO | awk '$1 == "url" {print "Homepage: " substr($0, index($0,"= ")+2)}' >> control
        cat .SRCINFO | awk 'BEGIN{res=""} $1 == "depends" {if (res == "") {res = substr($0, index($0,"= ")+2)} else {res = (res ", " substr($0, index($0,"= ")+2))}} END{print "Depends: " res}' >> control
      working-directory: ${{github.workspace}}/clients
    - name: show control file
      run: cat control
      working-directory: ${{github.workspace}}/clients
    - name: copy control file
      run: mkdir ${{github.workspace}}/target/DEBIAN && cp control ${{github.workspace}}/target/DEBIAN/control
      working-directory: ${{github.workspace}}/clients
    - name: ls
      run: ls -la
      working-directory: ${{github.workspace}}/target
    - name: create deb
      run: dpkg-deb --build ${{github.workspace}}/target .
    - name: ls2
      run: ls -la
    - name: Attest
      id: attest
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: '${{github.workspace}}/*.deb'
    - name: Copy attestation file
      if: startsWith(github.ref, 'refs/tags/')
      run: cp $BUNDLE deb-bundle-attestation.jsonl
      env:
        BUNDLE: ${{steps.attest.outputs.bundle-path}}
    - uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: '${{github.workspace}}/*.deb'
        if-no-files-found: error
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          *.deb
          deb-bundle-attestation.jsonl

  test-deb-package:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    needs: build-deb-package

    steps:
    - name: Install dependencies
      run: apt update && apt install -y nodejs
    - uses: actions/download-artifact@v4
      with:
        name: deb-package
    - name: Display structure of downloaded files
      run: ls -R
    - name: Install the package
      run: apt update && apt install -y ./*.deb
    - name: Run the check
      run: /usr/lib/restic-backup-client/index.js check

