name: build packages

on:
  push:


jobs:
  build-arch-package:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup builder user
      run: 'useradd -m builder && echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder && chmod -R 777 .'
    - name: Install dependencies
      run: pacman --noconfirm -Sy pacman-contrib namcap nodejs
    - name: update source hashes
      run: runuser -u builder -- updpkgsums
      working-directory: ${{github.workspace}}/clients
    - name: check PKGBUILD
      run: 'if [ -n "$(runuser -u builder -- namcap -m PKGBUILD)" ]; then (namcap PKGBUILD; exit 1) else (exit 0) fi'
      working-directory: ${{github.workspace}}/clients
    - name: makepkg
      run: runuser -u builder -- makepkg --syncdeps --noconfirm --rmdeps
      working-directory: ${{github.workspace}}/clients
    - name: Attest
      if: ${{ !env.ACT }}
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: '${{github.workspace}}/clients/*.pkg.tar.zst'
    - uses: actions/upload-artifact@v4
      with:
        name: arch-package
        path: '${{github.workspace}}/clients/*.pkg.tar.zst'
        if-no-files-found: error
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: 'clients/*.pkg.tar.zst'
  test-arch-package:
    runs-on: ubuntu-latest
    container: archlinux:base
    needs: build-arch-package

    steps:
    - name: install node
      run: pacman -Sy --noconfirm nodejs
    - uses: actions/download-artifact@v4
      with:
        name: arch-package
    - name: Display structure of downloaded files
      run: ls -R
    - name: Install the package
      run: pacman -U --noconfirm *.pkg.tar.zst
    - name: Run the check
      run: hello-world check
